### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by hugobowne** [EricSchles/investa_gator_v2#4]
hi eric,

I'm currently installing -- the following is stated:

Once you have everything dowloaded, you'll still need to do a few things:
1) create the database
2) download the nltk corpus
3) twilio credentials - you'll need to sign up for twilio and create your own creds there
twilio.creds is of the form (username,password).  Both username and password are strings.  They were saved with pickle.  

My question is: what do I create the database from? And how does the twilio account impact the project?

**Comment by ralren** [comment]
Download the database by running the models.py file.

**Comment by hugobowne** [comment]
got it!
